spring:
  application:
    name: district-designer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/districtDesignerBase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # Или update, если надо сохранять данные между запусками
    show-sql: true # Полезно для отладки, покажет SQL-запросы в консоль
    properties:
      hibernate:
        format_sql: true # Форматированный вывод SQL-запросов

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # Включаем логгирование SQL-запросов
